gui:
  timeFormat: "06-01-02 15:04"
  shortTimeFormat: "15:04"
  nerdFontsVersion: "3"
  showBranchCommitHash: true
  filterMode: fuzzy
git:
  merging:
    args: --no-ff
  autoFetch: false
  autoRefresh: false
  log:
    showWholeGraph: true
update:
  method: never
